name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 2

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest

      - name: Run Action
        run: |
          deno run \
            --allow-read \
            --allow-write \
            --allow-env \
            --allow-net \
            --allow-run \
            src/main/main.ts \
            --gitDiffFromHash="HEAD^1" \
            --gitDiffToHash="HEAD" \
            --outputDirectory="." \
            --outputFileName="test"
          cat test.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
